### ISSUE TITLE
编译失败：缺少 lib\x64\Debug\marl_d.lib

### ISSUE THREAD

**Issue by treert** [BenzzzX/Dots#1]
DotsTest 编译失败，缺少 lib\x64\Debug\marl_d.lib。

**Comment by SaeruHikari** [comment]
因为Test工程是VS工程独有的（暂时我们只完全覆盖windows测试），我们会在构建测试时把编译好的静态marl lib解压到DotsTest文件夹下。
![image](https://user-images.githubusercontent.com/39457738/114151167-6de32180-994f-11eb-9378-a31b8f3c7ae3.png)
我们马上会上传一个编译完成的marl静态库，解压成如上图路径即可通过链接。

**Comment by SaeruHikari** [comment]
已经上传依赖库到release

**Comment by SaeruHikari** [comment]
暂时关闭
